-- 코드를 입력하세요
SELECT DISTINCT
    C.CAR_ID,
    C.CAR_TYPE,
    FLOOR(C.DAILY_FEE * 30 * ( 1 - DISCOUNT_RATE / 100 ))
        AS FEE
FROM    
    CAR_RENTAL_COMPANY_CAR C
JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP 
    ON C.CAR_TYPE = DP.CAR_TYPE AND DP.DURATION_TYPE = '30일 이상'
WHERE
    C.CAR_TYPE IN ('세단','SUV')
    AND
    NOT EXISTS (SELECT 1 
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
                WHERE RH.CAR_ID = C.CAR_ID 
                AND RH.START_DATE <= '2022-11-30' 
                AND RH.END_DATE >= '2022-11-01'
                )
    AND (C.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE / 100)) >= 500000
    AND (C.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE / 100)) < 2000000
ORDER BY
    FEE DESC, CAR_TYPE, CAR_ID DESC;
    