-- 코드를 입력하세요
SELECT
    MR.MEMBER_NAME,
    RR.REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM
    MEMBER_PROFILE MR
JOIN
    REST_REVIEW RR ON MR.MEMBER_ID = RR.MEMBER_ID
WHERE
    MR.MEMBER_ID = (SELECT MEMBER_ID
                    FROM REST_REVIEW
                    GROUP BY MEMBER_ID
                    ORDER BY COUNT(*) DESC
                    LIMIT 1)
ORDER BY
    REVIEW_DATE, REVIEW_TEXT;