SELECT
    fi.ID,
    fni.FISH_NAME,
    fi.LENGTH
FROM
    FISH_INFO fi
JOIN
    FISH_NAME_INFO fni ON fi.FISH_TYPE = fni.FISH_TYPE
WHERE
    LENGTH = (SELECT MAX(LENGTH) FROM FISH_INFO fi2 WHERE fi2.FISH_TYPE = fi.FISH_TYPE)
ORDER BY
    ID;
